# this require will load ALL dependent jars
# the file example_jars.rb is generated by Jars::JarInstaller.install_jars
# see Rakefile
require 'example_jars'

# this is the jar compiled from src/main/java/**
require 'example.jar'
